if(EXISTS "/home/runner/work/mini-search-cpp/mini-search-cpp/_codeql_build_dir/tests/mini_search_tests[1]_tests.cmake")
  include("/home/runner/work/mini-search-cpp/mini-search-cpp/_codeql_build_dir/tests/mini_search_tests[1]_tests.cmake")
else()
  add_test(mini_search_tests_NOT_BUILT mini_search_tests_NOT_BUILT)
endif()
